### ISSUE TITLE
Adding Spinal HDL related repos

### ISSUE THREAD

**Issue by Jzjerry** [HKUST-GZ-VLSI/Design-Dataset#1]
Spinal HDL-based projects that could be added to this collection:

RISC-V cores:
VexRiscv:
https://github.com/SpinalHDL/VexRiscv
NaxRisv:
https://github.com/SpinalHDL/NaxRiscv
VexiiRiscv (W.I.P.) :
https://github.com/SpinalHDL/VexiiRiscv

SoCs:
SaxonSoc:
https://github.com/SpinalHDL/SaxonSoc
(There are two SoCs in the repo of VexRiscv as well)

Another suggestion: we can create a category for RISC-V cores cuz there are tons of them on Github.

**Comment by Jzjerry** [comment]
@YiKangOY 看看我的

**Comment by YiKangOY** [comment]
Thx, finished at 1dfab97.
